### ISSUE TITLE
[BUG] White screen after new update

### ISSUE THREAD

**Issue by SsimplyDan** [legendsayantan/MsRewards#23]
![Screenshot_2024 08 10_03 14 51 069](https://github.com/user-attachments/assets/8d4da495-cf38-4091-844e-94342662caed)

**Comment by legendsayantan** [comment]
Can you please provide more info? Like when and how often does this screen appear, any actions that triggers this, along with your device information?

**Comment by SsimplyDan** [comment]
After I got the new update on Samsung Galaxy S22 Ultra. Please could I use the older update because I am being restricted to use this. I also paid money for my points. From: Sayantan PaulSent: 10 August 2024 06:37 PMTo: legendsayantan/MsRewardsCc: SsimplyDan; AuthorSubject: Re: [legendsayantan/MsRewards] [BUG] White screen after new update (Issue #23) Can you please provide more info? Like when and how often does this screen appear, any actions that triggers this, along with your device information?—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by SsimplyDan** [comment]
Also happens when I boot it up. From: Sayantan PaulSent: 10 August 2024 06:37 PMTo: legendsayantan/MsRewardsCc: SsimplyDan; AuthorSubject: Re: [legendsayantan/MsRewards] [BUG] White screen after new update (Issue #23) Can you please provide more info? Like when and how often does this screen appear, any actions that triggers this, along with your device information?—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by legendsayantan** [comment]
Can you somehow find out the installed webview version? I have a hunch that this is not caused by the update, but something else.

**Comment by SsimplyDan** [comment]
I can’t find it, even on the apps list could I have a link to download it? From: Sayantan PaulSent: 11 August 2024 02:40 AMTo: legendsayantan/MsRewardsCc: SsimplyDan; AuthorSubject: Re: [legendsayantan/MsRewards] [BUG] White screen after new update (Issue #23) Can you somehow find out the installed webview version? I have a hunch that this is not caused by the update, but something else.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by legendsayantan** [comment]
You can find it here -
https://www.apkmirror.com/apk/google-inc/android-system-webview/
You need to have version 114 or older installed into the device, which I suspect that you had previously but now it's lost. 

The reason I released the new update is because the old app kept locking people out of it, so it was dangerous to keep using.... That means there is no problem free way to go back...

**Comment by SsimplyDan** [comment]
I’ve don’t and still get the white screen. This whole thing worked with no problems but now I spent money on this and now I can’t access it. Please make a version that I can use. From: Sayantan PaulSent: 11 August 2024 11:27 AMTo: legendsayantan/MsRewardsCc: SsimplyDan; AuthorSubject: Re: [legendsayantan/MsRewards] [BUG] White screen after new update (Issue #23) You can find it here -https://www.apkmirror.com/apk/google-inc/android-system-webview/You need to have version 114 or older installed into the device, which I suspect that you had previously but now it's lost.The reason I released the new update is because the old app kept locking people out of it, so it was dangerous to keep using.... That means there is no problem free way to go back...—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by legendsayantan** [comment]
Are you using Bluestacks emulator with a Samsung S22 ultra rom? This app is only designed to be reliable on real android devices, and I have an issue pinned with a warning about this. However I am slowly adding emulator support, but to use that users have to specifically ask for the permission. To ask for the permission, send an email at [legendsayantan@gmail.com](mailto://legendsayantan@gmail.com).

**Comment by SsimplyDan** [comment]
Yes exactly, I have sent permission to the email.
